Product page
dev-prabhat/e-commerce pull request #8
Opened 2022-02-09 12:56 UTC by dev-prabhat

2022-02-09 13:56 UTC, DivyanshSareen approved these changes
Looks good. Good to merge

2022-02-09 18:51 UTC, Muzammil-khan710 approved these changes
Good to merge. !

2022-02-09 18:54 UTC, varun13169 requested changes

2022-02-09 18:54 UTC, varun13169 commented on pages/productPage/productPage.css
> +}
nit on naming

filter -> sidebar
product -> content


as tomorrow you can change the filter to something else and product can be services as well.

2022-02-09 18:54 UTC, varun13169 commented on pages/productPage/productPage.css
> +  border-bottom: 1px solid var(--dark-theme-shade-20);
what does shade 20 means?

specify direction as well, eg: lighter or darker

2022-02-10 20:42 UTC, dev-prabhat commented on pages/productPage/productPage.css
> +  border-bottom: 1px solid var(--dark-theme-shade-20);
there are 5 shades of the same color with every increasing value shades are darker

2022-02-11 07:02 UTC, varun13169 approved these changes

2022-02-11 07:02 UTC, varun13169 commented on pages/productPage/productPage.css
> +}
Resolved.

2022-02-11 07:02 UTC, varun13169 commented on pages/productPage/productPage.css
> +  border-bottom: 1px solid var(--dark-theme-shade-20);
ok

2022-02-11 07:03 UTC, merged